version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./services:/app:Z
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: pi_dsm_5
      POSTGRES_USER: pi_dsm_5
      POSTGRES_DB: pi_dsm_5
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres

  postgres:
    image: postgres:15
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:Z
      - ./migrations:/docker-entrypoint-initdb.d:Z
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: pi_dsm_5
      POSTGRES_USER: pi_dsm_5
      POSTGRES_DB: pi_dsm_5
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres

networks:
  backend:
    driver: bridge
